# Generated by Django 3.2.3 on 2021-10-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=20)),
                ('what', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=300)),
                ('when', models.DateTimeField()),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReparationMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sous_famille', models.IntegerField()),
                ('pid', models.CharField(max_length=25)),
                ('date_sortie', models.DateField()),
                ('fournisseur', models.IntegerField()),
                ('obs', models.TextField()),
                ('date_modif', models.DateTimeField()),
                ('whomodif', models.TextField()),
                ('num_bon', models.TextField()),
                ('ville', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'reparation_mat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SortiPlateau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sorti_stock', models.IntegerField()),
                ('ancien_etat', models.TextField()),
                ('nouvelle_etat', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('date_sortie_plateau', models.DateField()),
                ('obs', models.TextField()),
                ('date_modif', models.DateTimeField()),
                ('whomodif', models.TextField()),
                ('num_bon', models.TextField()),
                ('ville', models.TextField()),
            ],
            options={
                'db_table': 'sorti_plateau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('tel1', models.CharField(blank=True, max_length=50, null=True)),
                ('tel2', models.CharField(blank=True, max_length=50, null=True)),
                ('tel3', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=80, null=True)),
                ('activite', models.CharField(blank=True, max_length=80, null=True)),
                ('obs', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('numero_serie', models.TextField()),
                ('id_fournisseur', models.IntegerField()),
                ('date_entree', models.DateTimeField(null=True)),
                ('bl', models.CharField(max_length=20)),
                ('facture', models.CharField(max_length=20)),
                ('quantite', models.IntegerField()),
                ('prix', models.CharField(max_length=5)),
                ('garantie', models.IntegerField()),
                ('date_deb_gar', models.DateField(null=True)),
                ('societe', models.CharField(max_length=13)),
                ('whomodif', models.CharField(max_length=20)),
                ('date_modif', models.DateTimeField(null=True)),
                ('num_bon', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'entree_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('garantie', models.IntegerField(blank=True, default='0', null=True)),
                ('dateen', models.DateTimeField(auto_now=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Familles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'familles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SousFamille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('marque', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('seuil', models.IntegerField()),
                ('pid1', models.CharField(max_length=20)),
                ('active', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3)),
                ('ville', models.CharField(choices=[('tunis', 'tunis'), ('sousse', 'sousse'), ('nice', 'nice')], max_length=6)),
                ('id_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.familles', verbose_name='the related famille')),
            ],
            options={
                'db_table': 'sous_famille',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(choices=[('argos', 'argos'), ('jupiter', 'jupiter'), ('ithaque', 'ithaque'), ('tanis', 'tanis'), ('comptabilite', 'comptabilite'), ('fumoire', 'fumoire')], max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(blank=True, max_length=50, null=True)),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.facture')),
                ('id_sous_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sousfamille')),
            ],
        ),
        migrations.CreateModel(
            name='SortiStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sorti', models.DateField()),
                ('quantite', models.IntegerField()),
                ('lieu', models.CharField(max_length=10)),
                ('obs', models.TextField()),
                ('whomodif', models.CharField(max_length=10)),
                ('date_modif', models.DateTimeField()),
                ('num_bon', models.CharField(max_length=20)),
                ('etat', models.CharField(max_length=1)),
                ('ville', models.CharField(max_length=6)),
                ('responsable', models.TextField()),
                ('voyant', models.TextField()),
                ('nom_voyant', models.TextField()),
                ('prenom_voyant', models.TextField()),
                ('id_entree_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.entreestock')),
            ],
            options={
                'db_table': 'sorti_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Historique_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(choices=[('argos', 'argos'), ('jupiter', 'jupiter'), ('ithaque', 'ithaque'), ('tanis', 'tanis'), ('comptabilite', 'comptabilite'), ('fumoire', 'fumoire')], max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('id_sous_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sousfamille')),
            ],
        ),
        migrations.AddField(
            model_name='entreestock',
            name='id_sous_famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sousfamille'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(max_length=20)),
                ('designation', models.TextField(max_length=20)),
                ('dateacquisition', models.DateField(blank=True, db_column='dateAcquisition', null=True)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('montant', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(choices=[('tunis', 'tunis'), ('sousse', 'sousse'), ('nice', 'nice')], max_length=6)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact')),
            ],
            options={
                'db_table': 'contrat',
                'managed': True,
            },
        ),
    ]
