# Generated by Django 3.2.8 on 2021-11-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='distinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(choices=[('argos', 'argos'), ('jupiter', 'jupiter'), ('ithaque', 'ithaque'), ('tanis', 'tanis'), ('comptabilite', 'comptabilite'), ('fumoire', 'fumoire')], max_length=50)),
                ('nom_dis', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sortistock',
            name='id_entree_stock',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='ReparationMat',
        ),
        migrations.DeleteModel(
            name='SortiPlateau',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entreestock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sousfamille',
            options={},
        ),
        migrations.RemoveField(
            model_name='historique_stock',
            name='export_to_CSV',
        ),
        migrations.AddField(
            model_name='historique_stock',
            name='ci',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fournisseur',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact', verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='sousfamille',
            name='active',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3, verbose_name='consommable'),
        ),
        migrations.AlterField(
            model_name='sousfamille',
            name='id_famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.familles', verbose_name='Les Articles'),
        ),
        migrations.AlterField(
            model_name='sousfamille',
            name='pid1',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ci',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id_sous_famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sousfamille', verbose_name='Article'),
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contrat',
            table=None,
        ),
        migrations.AlterModelTable(
            name='entreestock',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sousfamille',
            table=None,
        ),
        migrations.DeleteModel(
            name='SortiStock',
        ),
    ]
