# Generated by Django 3.2.8 on 2021-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211114_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_to',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
