# Generated by Django 3.2.8 on 2021-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_stock_issue_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='garantie',
        ),
        migrations.AddField(
            model_name='facture',
            name='Society',
            field=models.IntegerField(blank=True, choices=[('argos', 'argos'), ('jupiter', 'jupiter'), ('ithaque', 'ithaque'), ('tanis', 'tanis')], default='0', null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateen',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ref',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='Réference facture'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='garantie'),
        ),
    ]
