# Generated by Django 3.2.8 on 2021-11-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211114_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dateen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
