# Generated by Django 3.2.8 on 2021-11-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_facture_dateen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Society',
            field=models.CharField(blank=True, choices=[('argos', 'argos'), ('jupiter', 'jupiter'), ('ithaque', 'ithaque'), ('tanis', 'tanis')], default='0', max_length=50, null=True),
        ),
    ]
