# Generated by Django 3.2.8 on 2021-11-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_facture_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dateen',
            field=models.DateTimeField(),
        ),
    ]
