# Generated by Django 3.2.8 on 2021-11-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_facture_dateen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_to',
            field=models.CharField(choices=[('bureau1', 'ithaque : bureau1'), ('box1', 'jupiter : box1'), ('bureau4', 'tanis : bureau4'), ('box2', 'argos : box2'), ('bureau2', 'fumoire : bureau2'), ('bureau12', 'tanis : bureau12')], max_length=50),
        ),
    ]
