# Generated by Django 3.2.8 on 2021-11-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_stock_issue_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='issue_to',
            field=models.ForeignKey(default='Stock', on_delete=django.db.models.deletion.CASCADE, to='users.distinations', verbose_name='Emplacement'),
        ),
    ]
