# Generated by Django 3.2.8 on 2021-11-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211115_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinations',
            name='nom_dis',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
