# Generated by Django 3.2.8 on 2021-12-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_stock_issue_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique_stock',
            name='codeibar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historique_stock',
            name='issue_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
