# Generated by Django 3.2.8 on 2022-01-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_stock_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
