# Generated by Django 3.1.4 on 2022-01-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_task_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousfamille',
            name='ville',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
