# Generated by Django 3.1.4 on 2022-02-02 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220127_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sousfamille'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='designation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='montant',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='observation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='EntreeStock',
        ),
    ]
